AWSTemplateFormatVersion: 2010-09-09
Parameters:
  # common
  SysName:
    Type: String
    Default: helloWorld
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
    Default: dev
  SpaceChar:
    Type: String
    Default: '-'
  KeyPairName:
    Description: param for Tokyo or Osaka
    Type: String
    AllowedValues:
      - cassandra2
      - osaka-region
    Default: osaka-region

  # application-environment
  # VPC
  AvailabilityZone1:
    Description: param for Tokyo or Osaka
    Type: String
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1b
      - ap-northeast-1c
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3a
  AvailabilityZone2:
    Description: param for Tokyo or Osaka
    Type: String
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1b
      - ap-northeast-1c
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3c
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnet1CidrBlock:
    Type: String
    Default: 192.168.20.0/24
  FrontSubnet2CidrBlock:
    Type: String
    Default: 192.168.21.0/24
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnet1CidrBlock:
    Type: String
    Default: 192.168.30.0/24
  AppSubnet2CidrBlock:
    Type: String
    Default: 192.168.31.0/24

  # Bastion
  BastionEc2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  BastionEc2InstanceType:
    Type: String
    Default: t2.micro

  # Batch
  BatchImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  BatchEc2InstanceType:
    Type: String
    Default: t3.nano

  # BeansTalk
  SSLCertificateId:
    Type: String
    Default: arn:aws:acm:ap-northeast-1:498588106976:certificate/4b64b506-0eb9-415d-b210-efc08389b9a5
  S3BucketForFirstDeploy:
    Type: String
    Default: cf-templates-lpwe8q0rzy1m-ap-northeast-1
  DeployTargetForFirstDeploy:
    Type: String
    Default: helloworld-0.0.1-SNAPSHOT.jar

  # RDS
  Username:
    Description: Name of DB mater username.
    Type: String
    Default: admintest
  Password:
    Description: Name of DB mater user password.
    Type: String
    Default: a1111111
    NoEcho: true

  # development-environment
  # CodePipelineOfBeansTalk
  RepositoryUrl:
    Type: String
    Default: 'https://github.com/kaburankattara/helloworldBySpringBoot.git'
  FullRepositoryId:
    Type: String
    Default: 'kaburankattara/helloworldBySpringBoot'
  # CodePipelineOfBatch
  BuildedSource:
    Type: String
    Default: helloworld-0.0.1-SNAPSHOT.jar
  DeployTargetEC2Name:
    Type: String
    Default: helloWorld-dev-app

Resources:
  ApplicationEnvironment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/application-environment-template.yaml'
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        KeyPairName: !Ref KeyPairName
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        VpcCidrBlock: !Ref VpcCidrBlock
        FrontSubnet1CidrBlock: !Ref FrontSubnet1CidrBlock
        FrontSubnet2CidrBlock: !Ref FrontSubnet2CidrBlock
        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
        AppSubnet1CidrBlock: !Ref AppSubnet1CidrBlock
        AppSubnet2CidrBlock: !Ref AppSubnet2CidrBlock
        # Bastion
        BastionEc2ImageId: !Ref BastionEc2ImageId
        BastionEc2InstanceType: !Ref BastionEc2InstanceType
        # Batch
        BatchImageId: !Ref BatchImageId
        BatchEc2InstanceType: !Ref BatchEc2InstanceType
        # BeansTalk
        SSLCertificateId: !Ref SSLCertificateId
        S3BucketForFirstDeploy: !Ref S3BucketForFirstDeploy
        DeployTargetForFirstDeploy: !Ref DeployTargetForFirstDeploy
        # RDS
        Username: !Ref Username
        Password: !Ref Password

#  DevelopmentEnvironment:
#    Type: AWS::CloudFormation::Stack
#    DependsOn: ApplicationEnvironment
#    Properties:
#      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/development-environment-template.yaml'
#      Parameters:
#        SysName: !Ref SysName
#        Env: !Ref Env
#        SpaceChar: !Ref SpaceChar
#        RepositoryUrl: !Ref RepositoryUrl
#        FullRepositoryId: !Ref FullRepositoryId
#        BuildedSource: !Ref BuildedSource
#        DeployTargetEC2Name: !Ref DeployTargetEC2Name


