AWSTemplateFormatVersion: 2010-09-09
Parameters:
  # common
  SysName:
    Type: String
    Default: helloWorld
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
    Default: dev
  SpaceChar:
    Type: String
    Default: '-'
  KeyPairName:
    Description: param for Tokyo or Osaka
    Type: String
    AllowedValues:
      - cassandra2
      - osaka-region
    Default: osaka-region

  # application-environment
  # VPC
  AvailabilityZone1:
    Description: param for Tokyo or Osaka
    Type: String
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1b
      - ap-northeast-1c
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3a
  AvailabilityZone2:
    Description: param for Tokyo or Osaka
    Type: String
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1b
      - ap-northeast-1c
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3c
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnet1CidrBlock:
    Type: String
    Default: 192.168.20.0/24
  FrontSubnet2CidrBlock:
    Type: String
    Default: 192.168.21.0/24
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnet1CidrBlock:
    Type: String
    Default: 192.168.30.0/24
  AppSubnet2CidrBlock:
    Type: String
    Default: 192.168.31.0/24

  # Bastion
  BastionEc2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  BastionEc2InstanceType:
    Type: String
    Default: t2.micro

  # Batch
  BatchImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  BatchEc2InstanceType:
    Type: String
    Default: t2.micro

  # BeansTalk
  # Beanstalk環境で使用するソリューションスタック（プラットフォームバージョン）の名前
  BeansTalkSolutionStackName:
    Type: String
    Default: 64bit Amazon Linux 2 v3.2.12 running Corretto 8
  # Beanstalk管理下のEC2のインスタンスタイプ
  BeansTalkInstanceTypes:
    Type: String
    Default: t3.nano
  # Beanstalk管理下のEC2のオートスケーリングの最大サイズ
  BeansTalkAutoscalingMaxSize:
    Type: String
    Default: 3
  # Beanstalk管理下のEC2のオートスケーリングの最小サイズ
  BeansTalkAutoscalingMinSize:
    Type: String
    Default: 2
  # 通知の送信先となる E メールアドレス、Amazon SQS キュー、または URL
  BeansTalkNotificationEndpoint:
    Type: String
    Default: a@a
  # 証明書のARN
  BeansTalkSSLCertificateId:
    Description: param for Tokyo or Osaka
    Type: String
    Default: arn:aws:acm:ap-northeast-3:498588106976:certificate/27cf533d-6ca5-43b9-9ac9-35f1a5d8178f
    #Default: arn:aws:acm:ap-northeast-1:498588106976:certificate/4b64b506-0eb9-415d-b210-efc08389b9a5
  # 初回デプロイ時にデプロイするソースを格納しているバケット名
  BeansTalkS3BucketForFirstDeploy:
    Description: param for Tokyo or Osaka
    Type: String
    Default: cf-templates-lpwe8q0rzy1m-ap-northeast-3
    #Default: cf-templates-lpwe8q0rzy1m-ap-northeast-1
  # 初回デプロイ時にデプロイするソースファイル名
  BeansTalkDeployTargetForFirstDeploy:
    Type: String
    Default: helloworld-0.0.1-SNAPSHOT.jar

  # RDS
  RDSUsername:
    Description: Name of DB mater username.
    Type: String
    Default: admintest
  RDSPassword:
    Description: Name of DB mater user password.
    Type: String
    Default: a1111111
    NoEcho: true

  # development-environment
  # CodePipelineOfBeansTalk
  RepositoryUrl:
    Type: String
    Default: 'https://github.com/kaburankattara/helloworldBySpringBoot.git'
  FullRepositoryId:
    Type: String
    Default: 'kaburankattara/helloworldBySpringBoot'
  # CodePipelineOfBatch
  BuildedSource:
    Type: String
    Default: helloworld-0.0.1-SNAPSHOT.jar
  DeployTargetEC2Name:
    Type: String
    Default: helloWorld-dev-app

Resources:
  ApplicationEnvironment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/application-environment-template.yaml'
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        KeyPairName: !Ref KeyPairName
        # VPC
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        VpcCidrBlock: !Ref VpcCidrBlock
        FrontSubnet1CidrBlock: !Ref FrontSubnet1CidrBlock
        FrontSubnet2CidrBlock: !Ref FrontSubnet2CidrBlock
        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
        AppSubnet1CidrBlock: !Ref AppSubnet1CidrBlock
        AppSubnet2CidrBlock: !Ref AppSubnet2CidrBlock
        # Bastion
        BastionEc2ImageId: !Ref BastionEc2ImageId
        BastionEc2InstanceType: !Ref BastionEc2InstanceType
        # Batch
        BatchImageId: !Ref BatchImageId
        BatchEc2InstanceType: !Ref BatchEc2InstanceType
        # BeansTalk
        BeansTalkSolutionStackName: !Ref BeansTalkSolutionStackName
        BeansTalkInstanceTypes: !Ref BeansTalkInstanceTypes
        BeansTalkAutoscalingMaxSize: !Ref BeansTalkAutoscalingMaxSize
        BeansTalkAutoscalingMinSize: !Ref BeansTalkAutoscalingMinSize
        BeansTalkNotificationEndpoint: !Ref BeansTalkNotificationEndpoint
        BeansTalkSSLCertificateId: !Ref BeansTalkSSLCertificateId
        BeansTalkS3BucketForFirstDeploy: !Ref BeansTalkS3BucketForFirstDeploy
        BeansTalkDeployTargetForFirstDeploy: !Ref BeansTalkDeployTargetForFirstDeploy
        # RDS
        RDSUsername: !Ref RDSUsername
        RDSPassword: !Ref RDSPassword

#  DevelopmentEnvironment:
#    Type: AWS::CloudFormation::Stack
#    DependsOn: ApplicationEnvironment
#    Properties:
#      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/development-environment-template.yaml'
#      Parameters:
#        SysName: !Ref SysName
#        Env: !Ref Env
#        SpaceChar: !Ref SpaceChar
#        RepositoryUrl: !Ref RepositoryUrl
#        FullRepositoryId: !Ref FullRepositoryId
#        BuildedSource: !Ref BuildedSource
#        DeployTargetEC2Name: !Ref DeployTargetEC2Name


