AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - Prod
      - Stg
      - dev
  TypeFront:
    Type: String
    Default: front
  TypeApp:
    Type: String
    Default: app
  TypeBastion:
    Type: String
    Default: bastion
  SpaceChar:
    Type: String
    Default: '-'
  AvailabilityZone1:
    Type: String
    AllowedValues:
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3a
  AvailabilityZone2:
    Type: String
    AllowedValues:
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3c
  VpcName:
    Type: String
    Default: vpc
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnetName:
    Type: String
    Default: front-Subnet
  FrontSubnet1CidrBlock:
    Type: String
    Default: 192.168.20.0/24
  FrontSubnet2CidrBlock:
    Type: String
    Default: 192.168.21.0/24
  BastionSubnetName:
    Type: String
    Default: bastion-subnet
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnetName:
    Type: String
    Default: app-subnet
  AppSubnet1CidrBlock:
    Type: String
    Default: 192.168.30.0/24
  AppSubnet2CidrBlock:
    Type: String
    Default: 192.168.31.0/24
  InternetGatewayName:
    Type: String
    Default: internetGateway
  FrontRTName:
    Type: String
    Default: front-rt
  NatEIPName:
    Type: String
    Default: nat-ip
  NatGatewayName:
    Type: String
    Default: natGateway
  NatRTName:
    Type: String
    Default: nat-rt
  DefaultSecurityGroup:
    Type: String
    Default: default-sg
  SshSecurityGroup:
    Type: String
    Default: ssh-sg
  FrontSecurityGroup:
    Type: String
    Default: front-sg
  AppSecurityGroup:
    Type: String
    Default: app-sg


  MyBastionSubnetId:
    Type: String
  MySshSGId:
    Type: String
  MyAppSubnet1Id:
    Type: String
  MyAppSubnet2Id:
    Type: String
  MyAppSGId:
    Type: String
  MyFrontSubnet1Id:
    Type: String
  MyFrontSubnet2Id:
    Type: String
  MyFrontSGId:
    Type: String

Resources:

  MyBastionInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f1ffb565070e6947
      InstanceType: t2.micro
      KeyName: osaka-region
      NetworkInterfaces:
        - SubnetId: !Ref MyBastionSubnetId
          GroupSet:
            - !Ref MySshSGId
          AssociatePublicIpAddress: true
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeBastion}'

  MyAppInstance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f1ffb565070e6947
      InstanceType: t3.nano
      KeyName: osaka-region
      NetworkInterfaces:
        - SubnetId: !Ref MyAppSubnet1Id
          GroupSet:
            - !Ref MyAppSGId
          AssociatePublicIpAddress: false
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeApp}'

  MyAppInstance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f1ffb565070e6947
      InstanceType: t3.nano
      KeyName: osaka-region
      NetworkInterfaces:
        - SubnetId: !Ref MyAppSubnet2Id
          GroupSet:
            - !Ref MyAppSGId
          AssociatePublicIpAddress: false
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeApp}'

  MyFrontInstance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f1ffb565070e6947
      InstanceType: t3.nano
      KeyName: osaka-region
      NetworkInterfaces:
        - SubnetId: !Ref MyFrontSubnet1Id
          GroupSet:
            - !Ref MyFrontSGId
          AssociatePublicIpAddress: true
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeFront}'

  MyFrontInstance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f1ffb565070e6947
      InstanceType: t3.nano
      KeyName: osaka-region
      NetworkInterfaces:
        - SubnetId: !Ref MyFrontSubnet2Id
          GroupSet:
            - !Ref MyFrontSGId
          AssociatePublicIpAddress: true
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeFront}'
