AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
    Default: dev
  NlayerPublic:
    Type: String
    Default: public
  NlayerProtected:
    Type: String
    Default: protected
  NlayerPrivate:
    Type: String
    Default: private
  TypeFront:
    Type: String
    Default: front
  TypeApp:
    Type: String
    Default: app
  TypeBastion:
    Type: String
    Default: bastion
  TypeMail:
    Type: String
    Default: mail
  SpaceChar:
    Type: String
    Default: '-'
  AvailabilityZone1:
    Type: String
    AllowedValues:
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3a
  AvailabilityZone2:
    Type: String
    AllowedValues:
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-3c
  VpcName:
    Type: String
    Default: vpc
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnetName:
    Type: String
    Default: front-Subnet
  FrontSubnet1CidrBlock:
    Type: String
    Default: 192.168.20.0/24
  FrontSubnet2CidrBlock:
    Type: String
    Default: 192.168.21.0/24
  BastionSubnetName:
    Type: String
    Default: bastion-subnet
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnetName:
    Type: String
    Default: app-subnet
  AppSubnet1CidrBlock:
    Type: String
    Default: 192.168.30.0/24
  AppSubnet2CidrBlock:
    Type: String
    Default: 192.168.31.0/24
  InternetGatewayName:
    Type: String
    Default: internetGateway
  FrontRTName:
    Type: String
    Default: front-rt
  NatEIPName:
    Type: String
    Default: nat-ip
  NatGatewayName:
    Type: String
    Default: natGateway
  NatRTName:
    Type: String
    Default: nat-rt
  DefaultSecurityGroup:
    Type: String
    Default: default-sg
  SshSecurityGroup:
    Type: String
    Default: ssh-sg
  FrontSecurityGroup:
    Type: String
    Default: front-sg
  AppSecurityGroup:
    Type: String
    Default: app-sg
  Username:
    Description: Name of DB mater username.
    Type: String
    Default: admin
  Password:
    Description: Name of DB mater user password.
    Type: String
    NoEcho: true
  SSLCertificateId:
    Type: String



Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/vpc.yaml
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        VpcName: !Ref VpcName
        VpcCidrBlock: !Ref VpcCidrBlock
        FrontSubnetName: !Ref FrontSubnetName
        FrontSubnet1CidrBlock: !Ref FrontSubnet1CidrBlock
        FrontSubnet2CidrBlock: !Ref FrontSubnet2CidrBlock
        BastionSubnetName: !Ref BastionSubnetName
        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
        AppSubnetName: !Ref AppSubnetName
        AppSubnet1CidrBlock: !Ref AppSubnet1CidrBlock
        AppSubnet2CidrBlock: !Ref AppSubnet2CidrBlock
        InternetGatewayName: !Ref InternetGatewayName
        FrontRTName: !Ref FrontRTName
        NatEIPName: !Ref NatEIPName
        NatGatewayName: !Ref NatGatewayName
        NatRTName: !Ref NatRTName
        DefaultSecurityGroup: !Ref DefaultSecurityGroup
        SshSecurityGroup: !Ref SshSecurityGroup
        FrontSecurityGroup: !Ref FrontSecurityGroup
        AppSecurityGroup: !Ref AppSecurityGroup

#  Instance:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/ec2.yaml
#      Parameters:
#        SysName: !Ref SysName
#        Env: !Ref Env
#        TypeFront: !Ref TypeFront
#        TypeApp: !Ref TypeApp
#        TypeBastion: !Ref TypeBastion
#        SpaceChar: !Ref SpaceChar
#        AvailabilityZone1: !Ref AvailabilityZone1
#        AvailabilityZone2: !Ref AvailabilityZone2
#        VpcName: !Ref VpcName
#        VpcCidrBlock: !Ref VpcCidrBlock
#        FrontSubnetName: !Ref FrontSubnetName
#        FrontSubnet1CidrBlock: !Ref FrontSubnet1CidrBlock
#        FrontSubnet2CidrBlock: !Ref FrontSubnet2CidrBlock
#        BastionSubnetName: !Ref BastionSubnetName
#        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
#        AppSubnetName: !Ref AppSubnetName
#        AppSubnet1CidrBlock: !Ref AppSubnet1CidrBlock
#        AppSubnet2CidrBlock: !Ref AppSubnet2CidrBlock
#        InternetGatewayName: !Ref InternetGatewayName
#        FrontRTName: !Ref FrontRTName
#        NatEIPName: !Ref NatEIPName
#        NatGatewayName: !Ref NatGatewayName
#        NatRTName: !Ref NatRTName
#        DefaultSecurityGroup: !Ref DefaultSecurityGroup
#        SshSecurityGroup: !Ref SshSecurityGroup
#        FrontSecurityGroup: !Ref FrontSecurityGroup
#        AppSecurityGroup: !Ref AppSecurityGroup
#
#        MyBastionSubnetId: !GetAtt VPC.Outputs.MyBastionSubnetId # !GetAtt で受け渡す
#        MySshSGId: !GetAtt VPC.Outputs.MySshSGId # !GetAtt で受け渡す
#        MyAppSubnet1Id: !GetAtt VPC.Outputs.MyAppSubnet1Id # !GetAtt で受け渡す
#        MyAppSubnet2Id: !GetAtt VPC.Outputs.MyAppSubnet2Id # !GetAtt で受け渡す
#        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId # !GetAtt で受け渡す
#        MyFrontSubnet1Id: !GetAtt VPC.Outputs.MyFrontSubnet1Id # !GetAtt で受け渡す
#        MyFrontSubnet2Id: !GetAtt VPC.Outputs.MyFrontSubnet2Id # !GetAtt で受け渡す
#        MyFrontSGId: !GetAtt VPC.Outputs.MyFrontSGId # !GetAtt で受け渡す

#  RDS:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/rds.yaml
#      Parameters:
#        SystemName: !Ref SysName
#        Environment: !Ref Env
#        Username: !Ref Username
#        Password: !Ref Password
#        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
#        MyAppSubnetId: !GetAtt VPC.Outputs.MyAppSubnetId
#        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId

  BeansTalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/beanstalk.yaml
      Parameters:
        SystemName: !Ref SysName
        Environment: !Ref Env
        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
        MyAppSubnet1Id: !GetAtt VPC.Outputs.MyAppSubnet1Id
        MyAppSubnet2Id: !GetAtt VPC.Outputs.MyAppSubnet2Id
        MyFrontSubnet1Id: !GetAtt VPC.Outputs.MyFrontSubnet1Id
        MyFrontSubnet2Id: !GetAtt VPC.Outputs.MyFrontSubnet2Id
        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId
        SSLCertificateId: !Ref SSLCertificateId

#  Lambda:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/lambda.yaml
#      Parameters:
#        SystemName: !Ref SysName
#        Environment: !Ref Env
#        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
#        MyAppSubnetId: !GetAtt VPC.Outputs.MyAppSubnetId
#        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId

Outputs:
  SysName:
    Value: !Ref SysName
  Env:
    Value: !Ref Env
  TypeFront:
    Value: !Ref TypeFront
  TypeApp:
    Value: !Ref TypeApp
  TypeBastion:
    Value: !Ref TypeBastion
  SpaceChar:
    Value: !Ref SpaceChar
  AvailabilityZone1:
    Value: !Ref AvailabilityZone1
  AvailabilityZone2:
    Value: !Ref AvailabilityZone2
  VpcName:
    Value: !Ref VpcName
  VpcCidrBlock:
    Value: !Ref VpcCidrBlock
  FrontSubnetName:
    Value: !Ref FrontSubnetName
  FrontSubnet1CidrBlock:
    Value: !Ref FrontSubnet1CidrBlock
  FrontSubnet2CidrBlock:
    Value: !Ref FrontSubnet2CidrBlock
  BastionSubnetName:
    Value: !Ref BastionSubnetName
  BastionSubnetCidrBlock:
    Value: !Ref BastionSubnetCidrBlock
  AppSubnetName:
    Value: !Ref AppSubnetName
  AppSubnet1CidrBlock:
    Value: !Ref AppSubnet1CidrBlock
  AppSubnet2CidrBlock:
    Value: !Ref AppSubnet2CidrBlock
  InternetGatewayName:
    Value: !Ref InternetGatewayName
  FrontRTName:
    Value: !Ref FrontRTName
  NatEIPName:
    Value: !Ref NatEIPName
  NatGatewayName:
    Value: !Ref NatGatewayName
  NatRTName:
    Value: !Ref NatRTName
  DefaultSecurityGroup:
    Value: !Ref DefaultSecurityGroup
  SshSecurityGroup:
    Value: !Ref SshSecurityGroup
  FrontSecurityGroup:
    Value: !Ref FrontSecurityGroup
  AppSecurityGroup:
    Value: !Ref AppSecurityGroup