AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
    Default: dev
  SpaceChar:
    Type: String
    Default: '-'
  KeyPairName:
    Type: String

  # VPC
  TypeApp:
    Type: String
    Default: app
  AvailabilityZone1:
    Type: String
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1b
      - ap-northeast-1c
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-1a
  AvailabilityZone2:
    Type: String
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1b
      - ap-northeast-1c
      - ap-northeast-3a
      - ap-northeast-3b
      - ap-northeast-3c
    Default: ap-northeast-1c
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnet1CidrBlock:
    Type: String
    Default: 192.168.20.0/24
  FrontSubnet2CidrBlock:
    Type: String
    Default: 192.168.21.0/24
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnet1CidrBlock:
    Type: String
    Default: 192.168.30.0/24
  AppSubnet2CidrBlock:
    Type: String
    Default: 192.168.31.0/24

  # Bastion
  BastionEc2ImageId:
    Type: String
  BastionEc2InstanceType:
    Type: String

  # Batch
  BatchImageId:
    Type: String
  BatchEc2InstanceType:
    Type: String

  # BeansTalk
  SSLCertificateId:
    Type: String
  S3BucketForFirstDeploy:
    Type: String
  DeployTargetForFirstDeploy:
    Type: String

  # RDS
  Username:
    Description: Name of DB mater username.
    Type: String
    Default: admintest
  Password:
    Description: Name of DB mater user password.
    Type: String
    Default: a1111111
    NoEcho: true

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/vpc.yaml
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        VpcCidrBlock: !Ref VpcCidrBlock
        FrontSubnet1CidrBlock: !Ref FrontSubnet1CidrBlock
        FrontSubnet2CidrBlock: !Ref FrontSubnet2CidrBlock
        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
        AppSubnet1CidrBlock: !Ref AppSubnet1CidrBlock
        AppSubnet2CidrBlock: !Ref AppSubnet2CidrBlock

  Bastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/bastion.yaml
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        KeyPairName: !Ref KeyPairName
        MyBastionSubnetId: !GetAtt VPC.Outputs.MyBastionSubnetId
        MySshSGId: !GetAtt VPC.Outputs.MySshSGId
        Ec2ImageId: !Ref BastionEc2ImageId
        Ec2InstanceType: !Ref BastionEc2InstanceType

#  S3:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/s3.yaml

  BeansTalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/beanstalk.yaml
      Parameters:
        SystemName: !Ref SysName
        Environment: !Ref Env
        KeyPairName: !Ref KeyPairName
        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
        MyAppSubnet1Id: !GetAtt VPC.Outputs.MyAppSubnet1Id
        MyAppSubnet2Id: !GetAtt VPC.Outputs.MyAppSubnet2Id
        MyFrontSubnet1Id: !GetAtt VPC.Outputs.MyFrontSubnet1Id
        MyFrontSubnet2Id: !GetAtt VPC.Outputs.MyFrontSubnet2Id
        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId
        SSLCertificateId: !Ref SSLCertificateId
        S3BucketForFirstDeploy: !Ref S3BucketForFirstDeploy
        DeployTargetForFirstDeploy: !Ref DeployTargetForFirstDeploy

#  Batch:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/batch.yaml
#      Parameters:
#        SysName: !Ref SysName
#        Env: !Ref Env
#        TypeApp: !Ref TypeApp
#        SpaceChar: !Ref SpaceChar
#        KeyPairName: !Ref KeyPairName
#        MyAppSubnet1Id: !GetAtt VPC.Outputs.MyAppSubnet1Id
#        MyAppSGId: !GetAtt VPC.Outputs.MySshSGId
#        Ec2ImageId: !Ref BatchImageId
#        Ec2InstanceType: !Ref BatchEc2InstanceType

#  RDS:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/rds.yaml
#      Parameters:
#        SystemName: !Ref SysName
#        Environment: !Ref Env
#        Username: !Ref Username
#        Password: !Ref Password
#        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
#        MyBastionSubnetId: !GetAtt VPC.Outputs.MyBastionSubnetId
#        MyAppSubnet1Id: !GetAtt VPC.Outputs.MyAppSubnet1Id
#        MyAppSubnet2Id: !GetAtt VPC.Outputs.MyAppSubnet2Id
#        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
#        AppSubnet1CidrBlock: !Ref AppSubnet1CidrBlock
#        AppSubnet2CidrBlock: !Ref AppSubnet2CidrBlock
#        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId

#  Lambda:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/application-environment/lambda.yaml
#      Parameters:
#        SystemName: !Ref SysName
#        Environment: !Ref Env
#        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
#        MyAppSubnetId: !GetAtt VPC.Outputs.MyAppSubnet1Id
#        InstanceArn: !GetAtt Batch.Outputs.MyAppInstance1Arn
#        InstanceId: !GetAtt Batch.Outputs.MyAppInstance1Id


