AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
  SpaceChar:
    Type: String
    Default: '-'
  KeyPairName:
    Type: String
  TypeBastion:
    Type: String
    Default: bastion
  MyBastionSubnetId:
    Type: String
  MySshSGId:
    Type: String
  Ec2ImageId:
    Type: String
  Ec2InstanceType:
    Type: String

Resources:
  MyBastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Ec2ImageId
      InstanceType: !Ref Ec2InstanceType
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - SubnetId: !Ref MyBastionSubnetId
          GroupSet:
            - !Ref MySshSGId
          AssociatePublicIpAddress: true
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeBastion}'
