AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - Prod
      - Stg
      - dev
  TypeFront:
    Type: String
    Default: front
  TypeApp:
    Type: String
    Default: app
  TypeBastion:
    Type: String
    Default: bastion
  SpaceChar:
    Type: String
    Default: '-'
  AvailabilityZone1:
    Type: String
    Default: ap-northeast-1a
  VpcName:
    Type: String
    Default: vpc
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnetName:
    Type: String
    Default: front-Subnet
  FrontSubnetCidrBlock:
    Type: String
    Default: 192.168.20.0/24
  BastionSubnetName:
    Type: String
    Default: bastion-subnet
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnetName:
    Type: String
    Default: app-subnet
  AppSubnetCidrBlock:
    Type: String
    Default: 192.168.30.0/24
  InternetGatewayName:
    Type: String
    Default: internetGateway
  FrontRTName:
    Type: String
    Default: front-rt
  NatEIPName:
    Type: String
    Default: nat-ip
  NatGatewayName:
    Type: String
    Default: natGateway
  NatRTName:
    Type: String
    Default: nat-rt
  DefaultSecurityGroup:
    Type: String
    Default: default-sg
  SshSecurityGroup:
    Type: String
    Default: ssh-sg
  FrontSecurityGroup:
    Type: String
    Default: front-sg
  AppSecurityGroup:
    Type: String
    Default: app-sg


  MyBastionSubnetId:
    Type: String
  MySshSGId:
    Type: String
  MyAppSubnetId:
    Type: String
  MyAppSGId:
    Type: String
  MyFrontSubnetId:
    Type: String
  MyFrontSGId:
    Type: String

Resources:

  MyBastionInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0218d08a1f9dac831
      InstanceType: t2.micro
      KeyName: cassandra2
      NetworkInterfaces:
        - SubnetId: !Ref MyBastionSubnetId
          GroupSet:
            - !Ref MySshSGId
          AssociatePublicIpAddress: true
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeBastion}'
  MyAppInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0218d08a1f9dac831
      InstanceType: t2.micro
      KeyName: cassandra2
      NetworkInterfaces:
        - SubnetId: !Ref MyAppSubnetId
          GroupSet:
            - !Ref MyAppSGId
          AssociatePublicIpAddress: false
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeApp}'
  MyFrontInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0218d08a1f9dac831
      InstanceType: t2.micro
      KeyName: cassandra2
      NetworkInterfaces:
        - SubnetId: !Ref MyFrontSubnetId
          GroupSet:
            - !Ref MyFrontSGId
          AssociatePublicIpAddress: true
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}${TypeFront}'
