AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create RDS db instances.

Mappings:
  dev:
#    DBSubnet1a: { ID: !Ref MyAppSubnetId }
#    DBSubnet1c: { ID: !Ref MyAppSubnetId }
#    RdsSecurityGroup: { ID: !Ref MyAppSGId }
    DBInstance:
      Engine: aurora-postgresql
      EngineVersion: 10.16
      RDS1AvailabilityZone: ap-northeast-1a
      RDS2AvailabilityZone: ap-northeast-1c
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 13:00-13:30
      ClusterPreferredMaintenanceWindow: tue:13:30-tue:14:00
      InstancePreferredMaintenanceWindow: wed:13:30-wed:14:00
      DatabaseName: chiba_db
      AutoMinorVersionUpgrade: true
      DBInstanceClass: db.t3.medium
    DBParameterGroup:
      DBEngineFamily: aurora-postgresql10

Parameters:
  Environment:
    Description: Type of this environment.
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - staging
      - dev
  SystemName:
    Description: Name of this system.
    Type: String
    Default: chiba-rds
  Username:
    Description: Name of DB mater username.
    Type: String
    Default: admintest
  Password:
    Description: Name of DB mater user password.
    Type: String
    NoEcho: true

  MyVpcId:
    Type: String
  MyAppSubnetId:
    Type: String
  MyAppSGId:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - SystemName
          - Environment
      - Label:
          default: RDS DB instace Configuration
        Parameters:
          - Username
          - Password

Resources:
  # IAM Role for enhanced monitoring
  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${Environment}-rds-monitoring-role
      Path: /
      AssumeRolePolicyDocument:
        !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "monitoring.rds.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole


  RDSCluster:
    Properties:
      DBClusterParameterGroupName:
        Ref: RDSDBClusterParameterGroup
      DBSubnetGroupName: 'dbsubnetgroup'
      Engine: aurora-postgresql
      EngineVersion: 10.16
      MasterUserPassword:
        Ref: Password
      MasterUsername:
        Ref: Username
    Type: "AWS::RDS::DBCluster"
  RDSDBInstance1:
    Properties:
      AvailabilityZone: ap-northeast-1a
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass: db.t3.medium
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      DBSubnetGroupName: 'dbsubnetgroup'
      Engine: aurora-postgresql
      EngineVersion: 10.16
      PubliclyAccessible: "false"
    Type: "AWS::RDS::DBInstance"
  RDSDBInstance2:
    Properties:
      AvailabilityZone: ap-northeast-1c
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass: db.t3.medium
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      DBSubnetGroupName: 'dbsubnetgroup'
      Engine: aurora-postgresql
      EngineVersion: 10.16
      PubliclyAccessible: "false"
    Type: "AWS::RDS::DBInstance"





  # DB subnet group
#  DBSubnetGroup:
  dbsubnetgroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: 'dbsubnetgroup'
      DBSubnetGroupDescription: !Sub ${SystemName}-${Environment}-db-subnet-group
      SubnetIds:
        - !Ref MyAppSubnetId
        - !Ref MyRdsSubnet
#        - !FindInMap [ !Ref Environment, DBSubnet1c, ID ]
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${Environment}-db-subnet-group'

  # DB Cluster Parameter Group
  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub ${SystemName}-${Environment}-db-cluster-param-group
      Family: !FindInMap [ !Ref Environment, DBParameterGroup, DBEngineFamily ]
      Parameters:
        client_encoding: 'UTF8'
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${Environment}-db-cluster-param-group'

  # DB parameter group
  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub ${SystemName}-${Environment}-db-param-group
      Family: !FindInMap [ !Ref Environment, DBParameterGroup, DBEngineFamily ]
      Parameters: {}
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${Environment}-db-param-group'




  MyRdsSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 192.168.31.0/24
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Environment}-db-Subnet'
      VpcId: !Ref MyVpcId