AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
  NlayerPublic:
    Type: String
    Default: public
  NlayerProtected:
    Type: String
    Default: protected
  NlayerPrivate:
    Type: String
    Default: private
  TypeFront:
    Type: String
    Default: front
  TypeApp:
    Type: String
    Default: app
  TypeBastion:
    Type: String
    Default: bastion
  TypeMail:
    Type: String
    Default: mail
  SpaceChar:
    Type: String
    Default: '-'
  AvailabilityZone1:
    Type: String
    Default: ap-northeast-1a
  VpcName:
    Type: String
    Default: vpc
  VpcCidrBlock:
    Type: String
    Default: 192.168.16.0/20
  FrontSubnetName:
    Type: String
    Default: front-Subnet
  FrontSubnetCidrBlock:
    Type: String
    Default: 192.168.20.0/24
  BastionSubnetName:
    Type: String
    Default: bastion-subnet
  BastionSubnetCidrBlock:
    Type: String
    Default: 192.168.17.0/24
  AppSubnetName:
    Type: String
    Default: app-subnet
  AppSubnetCidrBlock:
    Type: String
    Default: 192.168.30.0/24
  InternetGatewayName:
    Type: String
    Default: internetGateway
  FrontRTName:
    Type: String
    Default: front-rt
  NatEIPName:
    Type: String
    Default: nat-ip
  NatGatewayName:
    Type: String
    Default: natGateway
  NatRTName:
    Type: String
    Default: nat-rt
  DefaultSecurityGroup:
    Type: String
    Default: default-sg
  SshSecurityGroup:
    Type: String
    Default: ssh-sg
  FrontSecurityGroup:
    Type: String
    Default: front-sg
  AppSecurityGroup:
    Type: String
    Default: app-sg
  Username:
    Description: Name of DB mater username.
    Type: String
    Default: admin
  Password:
    Description: Name of DB mater user password.
    Type: String
    NoEcho: true

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/vpc.yaml
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        AvailabilityZone1: !Ref AvailabilityZone1
        VpcName: !Ref VpcName
        VpcCidrBlock: !Ref VpcCidrBlock
        FrontSubnetName: !Ref FrontSubnetName
        FrontSubnetCidrBlock: !Ref FrontSubnetCidrBlock
        BastionSubnetName: !Ref BastionSubnetName
        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
        AppSubnetName: !Ref AppSubnetName
        AppSubnetCidrBlock: !Ref AppSubnetCidrBlock
        InternetGatewayName: !Ref InternetGatewayName
        FrontRTName: !Ref FrontRTName
        NatEIPName: !Ref NatEIPName
        NatGatewayName: !Ref NatGatewayName
        NatRTName: !Ref NatRTName
        DefaultSecurityGroup: !Ref DefaultSecurityGroup
        SshSecurityGroup: !Ref SshSecurityGroup
        FrontSecurityGroup: !Ref FrontSecurityGroup
        AppSecurityGroup: !Ref AppSecurityGroup

#  Instance:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/ec2.yaml
#      Parameters:
#        SysName: !Ref SysName
#        Env: !Ref Env
#        TypeFront: !Ref TypeFront
#        TypeApp: !Ref TypeApp
#        TypeBastion: !Ref TypeBastion
#        SpaceChar: !Ref SpaceChar
#        AvailabilityZone1: !Ref AvailabilityZone1
#        VpcName: !Ref VpcName
#        VpcCidrBlock: !Ref VpcCidrBlock
#        FrontSubnetName: !Ref FrontSubnetName
#        FrontSubnetCidrBlock: !Ref FrontSubnetCidrBlock
#        BastionSubnetName: !Ref BastionSubnetName
#        BastionSubnetCidrBlock: !Ref BastionSubnetCidrBlock
#        AppSubnetName: !Ref AppSubnetName
#        AppSubnetCidrBlock: !Ref AppSubnetCidrBlock
#        InternetGatewayName: !Ref InternetGatewayName
#        FrontRTName: !Ref FrontRTName
#        NatEIPName: !Ref NatEIPName
#        NatGatewayName: !Ref NatGatewayName
#        NatRTName: !Ref NatRTName
#        DefaultSecurityGroup: !Ref DefaultSecurityGroup
#        SshSecurityGroup: !Ref SshSecurityGroup
#        FrontSecurityGroup: !Ref FrontSecurityGroup
#        AppSecurityGroup: !Ref AppSecurityGroup
#
#        MyBastionSubnetId: !GetAtt VPC.Outputs.MyBastionSubnetId # !GetAtt で受け渡す
#        MySshSGId: !GetAtt VPC.Outputs.MySshSGId # !GetAtt で受け渡す
#        MyAppSubnetId: !GetAtt VPC.Outputs.MyAppSubnetId # !GetAtt で受け渡す
#        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId # !GetAtt で受け渡す
#        MyFrontSubnetId: !GetAtt VPC.Outputs.MyFrontSubnetId # !GetAtt で受け渡す
#        MyFrontSGId: !GetAtt VPC.Outputs.MyFrontSGId # !GetAtt で受け渡す

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/rds.yaml
      Parameters:
        SystemName: !Ref SysName
        Environment: !Ref Env
        Username: !Ref Username
        Password: !Ref Password
        MyVpcId: !GetAtt VPC.Outputs.MyVpcId
        MyAppSubnetId: !GetAtt VPC.Outputs.MyAppSubnetId
        MyAppSGId: !GetAtt VPC.Outputs.MyAppSGId

Outputs:
  SysName:
    Value: !Ref SysName
  Env:
    Value: !Ref Env
  TypeFront:
    Value: !Ref TypeFront
  TypeApp:
    Value: !Ref TypeApp
  TypeBastion:
    Value: !Ref TypeBastion
  SpaceChar:
    Value: !Ref SpaceChar
  AvailabilityZone1:
    Value: !Ref AvailabilityZone1
  VpcName:
    Value: !Ref VpcName
  VpcCidrBlock:
    Value: !Ref VpcCidrBlock
  FrontSubnetName:
    Value: !Ref FrontSubnetName
  FrontSubnetCidrBlock:
    Value: !Ref FrontSubnetCidrBlock
  BastionSubnetName:
    Value: !Ref BastionSubnetName
  BastionSubnetCidrBlock:
    Value: !Ref BastionSubnetCidrBlock
  AppSubnetName:
    Value: !Ref AppSubnetName
  AppSubnetCidrBlock:
    Value: !Ref AppSubnetCidrBlock
  InternetGatewayName:
    Value: !Ref InternetGatewayName
  FrontRTName:
    Value: !Ref FrontRTName
  NatEIPName:
    Value: !Ref NatEIPName
  NatGatewayName:
    Value: !Ref NatGatewayName
  NatRTName:
    Value: !Ref NatRTName
  DefaultSecurityGroup:
    Value: !Ref DefaultSecurityGroup
  SshSecurityGroup:
    Value: !Ref SshSecurityGroup
  FrontSecurityGroup:
    Value: !Ref FrontSecurityGroup
  AppSecurityGroup:
    Value: !Ref AppSecurityGroup