AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
    Default: dev
  SpaceChar:
    Type: String
  PipelineEnvironmentName:
    Type: String
  FullRepositoryId:
    Type: String
  ArtifactBucketName:
    Type: String
  BuildedSource:
    Type: String
  DeployTargetEC2Name:
    Type: String

  # IAM
  CodePipelineServiceRoleArn:
    Type: String
  CodebuildRoleArn:
    Type: String
  CodeDeployServiceRoleArn:
    Type: String

  # SourceConnection
  ConnectionArn:
    Type: String

  # CodeBuild
  CodeBuildProjectName:
    Type: String

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineEnvironmentName
      RoleArn: !Ref CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: master
                OutputArtifactFormat: CODE_ZIP
              RunOrder: 1
              OutputArtifacts:
                - Name: App
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
              RunOrder: 1
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: MyApp
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
              RunOrder: 1
              InputArtifacts:
                - Name: MyApp

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}application'
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: CodeDeployApplication
    Properties:
      ApplicationName: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}application'
#      Deployment:
#        Revision:
#          RevisionType: S3
#          S3Location:
#            Bucket: !Ref ArtifactBucketName
#            BundleType: zip
#            Key: !Ref BuildedSource
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentGroupName: !Sub '${SysName}${SpaceChar}${Env}${SpaceChar}deployment${SpaceChar}group'
      DeploymentStyle:
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      Ec2TagFilters:
        - Key: Name
          Type: KEY_AND_VALUE
          Value: !Ref DeployTargetEC2Name
      ServiceRoleArn: !Ref CodeDeployServiceRoleArn

