AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CodeBuildProjectName:
    Type: String
  ArtifactBucketName:
    Type: String
  RepositoryUrl:
    Type: String

  # IAM
  CodebuildRoleArn:
    Type: String

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      Description: A description about my project
      ServiceRole: !Ref CodebuildRoleArn
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucketName
        Name: /
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
# 環境変数
#        EnvironmentVariables:
#          - Name: varName
#            Type: varType
#            Value: varValue
      Source:
        Auth:
          Type: OAUTH
        Location: !Ref RepositoryUrl
        Type: GITHUB

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
