AWSTemplateFormatVersion: '2010-09-09'
Parameters:

#  CodeBuildProjectName:
#    Type: String
#    Default: 'helloWorld'
  RepositoryUrl:
    Type: String
    Default: 'https://github.com/kaburankattara/helloworldBySpringBoot.git'
  PipelineEnvironmentName:
    Type: String
    Default: 'helloWorld'
#  S3BucketName:
#    Type: String
#    Default: 'my-beanstalk-tokyo'

Resources:

  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/s3.yaml

  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codepipeline.yaml'
      Parameters:
        PipelineEnvironmentName: !Ref PipelineEnvironmentName
        RepositoryUrl: !Ref RepositoryUrl
        ArtifactBucketName: !GetAtt S3.Outputs.S3BucketName




#  CodeBuild:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codebuild.yaml'
#      Parameters:
#        CodeBuildProjectName: !Ref CodeBuildProjectName
#        RepositoryUrl: !Ref RepositoryUrl
#        S3BucketName: !Ref S3BucketName

#Outputs:
#  CodeBuildProjectName:
#    Value: !Ref CodeBuildProjectName
#  RepositoryUrl:
#    Value: !Ref RepositoryUrl
#  S3BucketName:
#    Value: !Ref S3BucketName
