AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
  SpaceChar:
    Type: String
  RepositoryUrl:
    Type: String
  PipelineEnvironmentName:
    Type: String
  FullRepositoryId:
    Type: String

Resources:

  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/s3.yaml

  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codepipeline.yaml'
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        PipelineEnvironmentName: !Ref PipelineEnvironmentName
        RepositoryUrl: !Ref RepositoryUrl
        FullRepositoryId: !Ref FullRepositoryId
        ArtifactBucketName: !GetAtt S3.Outputs.S3BucketName




#  CodeBuild:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codebuild.yaml'
#      Parameters:
#        CodeBuildProjectName: !Ref CodeBuildProjectName
#        RepositoryUrl: !Ref RepositoryUrl
#        S3BucketName: !Ref S3BucketName

#Outputs:
#  CodeBuildProjectName:
#    Value: !Ref CodeBuildProjectName
#  RepositoryUrl:
#    Value: !Ref RepositoryUrl
#  S3BucketName:
#    Value: !Ref S3BucketName
