AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SysName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - prod
      - stag
      - dev
  SpaceChar:
    Type: String
  RepositoryUrl:
    Type: String
  PipelineEnvironmentName:
    Type: String
  FullRepositoryId:
    Type: String

Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/iam.yaml

  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/s3.yaml

  SourceConnection:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/sourceconnection.yaml
      Parameters:
        SysName: !Ref SysName

  CodeBuild:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codebuild.yaml
      Parameters:
        CodeBuildProjectName: !Ref PipelineEnvironmentName
        ArtifactBucketName: !GetAtt S3.Outputs.S3BucketName
        RepositoryUrl: !Ref RepositoryUrl
        # IAM
        CodebuildRoleArn: !GetAtt IAM.Outputs.CodebuildRoleArn

#  CodePipelineOfBeansTalk:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codepipeline.yaml'
#      Parameters:
#        SysName: !Ref SysName
#        Env: !Ref Env
#        SpaceChar: !Ref SpaceChar
#        PipelineEnvironmentName: !Ref PipelineEnvironmentName
#        RepositoryUrl: !Ref RepositoryUrl
#        FullRepositoryId: !Ref FullRepositoryId
#        ArtifactBucketName: !GetAtt S3.Outputs.S3BucketName
#        # IAM
#        CodePipelineServiceRoleArn: !GetAtt IAM.Outputs.CodePipelineServiceRoleArn
#        CodebuildRoleArn: !GetAtt IAM.Outputs.CodebuildRoleArn
#        # SourceConnection
#        ConnectionArn: !GetAtt SourceConnection.Outputs.ConnectionArn
#        # CodeBuild
#        CodeBuildProjectName: !GetAtt CodeBuild.Outputs.CodeBuildProjectName

  CodePipelineOfBatch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-lpwe8q0rzy1m-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/development-environment/codepipelineOfBatch.yaml'
      Parameters:
        SysName: !Ref SysName
        Env: !Ref Env
        SpaceChar: !Ref SpaceChar
        PipelineEnvironmentName: !Ref PipelineEnvironmentName
        RepositoryUrl: !Ref RepositoryUrl
        FullRepositoryId: !Ref FullRepositoryId
        # S3
        ArtifactBucketName: !GetAtt S3.Outputs.S3BucketName
        # IAM
        CodePipelineServiceRoleArn: !GetAtt IAM.Outputs.CodePipelineServiceRoleArn
        CodebuildRoleArn: !GetAtt IAM.Outputs.CodebuildRoleArn
        CodeDeployServiceRoleArn: !GetAtt IAM.Outputs.CodeDeployServiceRoleArn
        # SourceConnection
        ConnectionArn: !GetAtt SourceConnection.Outputs.ConnectionArn
        # CodeBuild
        CodeBuildProjectName: !GetAtt CodeBuild.Outputs.CodeBuildProjectName