AWSTemplateFormatVersion: 2010-09-09


Resources:

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName : aws-codedeploy-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployDeployerAccess
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

#  CodeDeployServiceRolePolicies:
#    Type: AWS::IAM::Policy
#    Properties:
#      PolicyName: CreateDeployment-Policy
#      PolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Action: codedeploy:CreateDeployment
#            Resource: "*"
#      Roles:
#        - !Ref CodeDeployServiceRole

  CodeDeployEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName : codedeploy-ec2-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  CodeDeployEc2RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: codedeploy-ec2-role-policies
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:Get*"
              - "s3:List*"
            Effect: Allow
            Resource: "*"
      Roles:
        - !Ref CodeDeployEc2Role

  CodeDeployEc2RoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref CodeDeployEc2Role

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: helloWorld
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: helloWorld
      Deployment:
        Revision:
          RevisionType: S3
          S3Location:
            Bucket: my-beanstalk-tokyo
            BundleType: zip
            Key: helloworld-0.0.1-SNAPSHOT.jar
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentGroupName: helloWorld-DeploymentGroup
      DeploymentStyle:
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      Ec2TagFilters:
        - Key: Name
          Type: KEY_AND_VALUE
          Value: helloWorld-dev-app
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      
Outputs:
  CodeDeployEc2RoleProfileId:
    Value: !Ref CodeDeployEc2RoleProfile